# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Values.service.name }}
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: control.local
#     http:
#       paths:
#       - path: /ai(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: {{ .Values.service.name }}
#             port:
#               number: 5000