apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name }}
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.clusterName }}.local
    http:
      paths:
      - path: /ai(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.deployment.name }}
            port:
              number: 5000