apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-constrained-ai.fullname" . }}
  labels:
    {{- include "resource-constrained-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "resource-constrained-ai.selectorLabels" . | nindent 4 }}