replicaCount: 1

image:
  repository: pidgeot72/resource-constrainted-ai
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}