apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-ingress
  name: app-ingress
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 1883
    protocol: TCP
    targetPort: 1883
    name: mqtt
  selector:
    app: app-ingress
  type: ClusterIP