replicaCount: 1
columnName: test
configmapName: test
image:
  repository: pidgeot72/resource-constrainted-ai
  tag: latest
  pullPolicy: Always
clusterName: ai
isCentralAI: False
deployment:
  name: ai
container:
  name: ai

resultEndPoint: test.com

service:
  name: ai
  type: ClusterIP
  port: 5000
replicaCount: 1
resources:
  limits:
    cpu: ".1"
    memory: "64Mi"
  requests:
    cpu: "0.1"
    memory: "32Mi"

env:
  - name: COLUMN_NAME
    value: ""
  - name: CLUSTER_NAME
    value: ""
  - name: FILE_NAME
    value: ""
  - name: MQTT_IP
    value: 0